# Generated by Django 2.2.6 on 2019-10-23 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='photo_size',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
