# Generated by Django 2.2.6 on 2019-10-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
